### ISSUE TITLE
GitHub Action - service "cli" is not running container #1

### ISSUE THREAD

**Issue by ynnoig** [spryker/docker-sdk#380] opened 2022-10-14 08:57 UTC
### Which release, branch or hash of Docker SDK are you using?
1.49.4

### Which operating system (platform/version/architecture) are you using?
Linux Ubuntu on GitHub Actions

### What is the issue that you're experiencing?
Sometimes in ci jobs that use docker-sdk we have the following error:
`service "cli" is not running container #1
/home/runner/work/project/project/docker/deployment/default/bin/service/database/postgres.sh: line 49: [: : integer expression expected`

#### What are the steps to reproduce the issue?
```
  php-81-postgresql-integration-alpine:
    name: "PHP 8.1 / PostgreSQL / Integration / Alpine"
    runs-on: ubuntu-latest
    env:
      ...

    steps:
    ...

      - name: Run docker
        run: |
          git clone <docker-sdk latest>
          docker/sdk boot -v deploy.ci.integration.yml
          docker/sdk up -t << Here happened the error!
          docker/sdk testing console queue:worker:start --stop-when-empty
          docker/sdk testing codecept run -c codeception.ci.integration.yml
```
#### What is the expected result of these steps in the absence of the issue?
That docker sdk start

#### What is the actual result?
Github Workflow stopped with exit code 1

### What possible solutions and/or workarounds for the issue do you see?
I don't know

### Is there any other information that might be helpful?
I think not

**Comment by alexanderM91** [comment] 2022-10-14 09:08
Hey @ynnoig,
please pull the latest master of the docker/sdk.

**Comment by alexanderM91** [comment] 2022-10-14 09:45
Hey @ynnoig,

Could you please help us to understand the root cause and answer for several questions? 
- Do you have the same behaviour locally or does it show up only in CI?
- Does CI stop execution or continue execution?
- Did you have this problem with the previous release?

**Comment by ynnoig** [comment] 2022-10-14 09:48
> Hey @ynnoig,
> 
> Could you please help us to understand the root cause and answer for several questions?
> 
> * Do you have the same behaviour locally or does it show up only in CI?
> * Does CI stop execution or continue execution?
> * Did you have this problem with the previous release?

* Only in CI (GitHub Actions)
* Stop Execution, I think due bash error in postgres.sh
* Yes, but always sometime (i.e. one or two times per week)

Thank u for your reply!

**Comment by alexanderM91** [comment] 2022-10-14 11:18
Cool, thanks a lot, @ynnoig, for your accurate and meaningful response.
We will put it into our backlog and mark as a bug with normal priority.

cc: @alexfoxpetrov

**Comment by alexanderM91** [comment] 2022-10-26 09:55
Hi @ynnoig,
do you have any updates here?
Also, did you have a chance to reproduce it locally?
Unfortunately, without a proper test case we cannot reproduce and fix it as our attempts were unsuccessful.

**Comment by ynnoig** [comment] 2022-10-26 11:59
Hi @alexanderM91 

with the fix (https://github.com/spryker/docker-sdk/pull/381) from @kalaputsik it works better... We had only on monday again a case with this error but not clear why.  @kalaputsik  has been notified from me about this case via Slack.

Locally runs always, only on GH Actions there was the problem.

I think that the optimization from @kalaputsik  can be merged.

**Comment by alexanderM91** [comment] 2022-11-08 14:57
Hi, the changes have been merged into the latest master.

**Closed** 2022-11-08 14:58 UTC
Labels: bug, solved
