### ISSUE TITLE
NPM permission issue

### ISSUE THREAD

**Issue by ghost** [spryker/docker-sdk#77] opened 2020-03-09 14:28 UTC
There was an issue when I ran the command ``` docker/sdk up ``` about file and directories permissions with npm

**Comment by marek-obuchowicz** [comment] 2020-03-09 15:14
@mostafaahamidmanon Thanks for this report. Could you please be more specific and provide full output + any additional information you saw about file/directory permissions?

**Comment by sprymiker** [comment] 2020-03-11 15:36
Related to https://github.com/nodejs/docker-node/issues/1126

**Comment by sprymiker** [comment] 2020-03-11 15:38
Will be fixed by https://github.com/spryker/docker-sdk/pull/79/files

**Comment by mostafaahamidmanon** [comment] 2020-03-16 19:44
Thanks @sprymiker  @marek-obuchowicz guys

**Comment by mostafaahamidmanon** [comment] 2020-03-16 19:48
That is the only solution over the whole internet for now to use ``` yarn ``` or you can append this: ``` --unsafe-perm=true --allow-root ``` to ``` npm install ``` command which is completely risky.

Thanks guys

**Comment by mostafaahamidmanon** [comment] 2020-03-16 20:47
Here is the screenshot @marek-obuchowicz 

https://imgur.com/2rSGsQW

Thanks alot

**Comment by mostafaahamidmanon** [comment] 2020-03-31 06:26
Still no news guys?

**Comment by sprymiker** [comment] 2020-04-04 16:27
Hello Mostafa,

Have you tried the latest versions?

https://github.com/spryker/docker-sdk/pull/79 should solve the issue.

Please, confirm or deny it works now. Thanks.

**Comment by sprymiker** [comment] 2020-05-29 15:54
Closing due to inactivity and the fact the issue is not reproducible any more.

**Closed by sprymiker** 2020-05-29 15:54 UTC
